// <auto-generated />
using System;
using IsbaSatisWeb.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IsbaSatisWeb.Persistence.Migrations
{
    [DbContext(typeof(IsbaSatisWebDbContext))]
    partial class IsbaSatisWebDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IsbaSatisWeb.Core.Domain.Entities.Common.BaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Aciklama");

                    b.Property<DateTime?>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("DuzenlenmeTarihi");

                    b.Property<string>("Duzenleyen")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("Duzenleyen");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("EklenmeTarihi");

                    b.Property<string>("Ekleyen")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("Ekleyen");

                    b.Property<int>("MyProperty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("IsbaSatisWeb.Core.Domain.Entities.Banka", b =>
                {
                    b.HasBaseType("IsbaSatisWeb.Core.Domain.Entities.Common.BaseEntity");

                    b.Property<string>("Bankasi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Bankasi");

                    b.Property<string>("HesapIsmi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HesapIsmi");

                    b.Property<string>("HesapKodu")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("HesapKodu");

                    b.Property<string>("HesapNo")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("HesapNo");

                    b.Property<string>("IbanNo")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)")
                        .HasColumnName("IbanNo");

                    b.Property<string>("Sube")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Sube");

                    b.Property<string>("YetkiliAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("YetkiliAdi");

                    b.Property<string>("YetkiliTelefonu")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("YetkiliTelefonu");

                    b.ToTable("Bankalar", (string)null);
                });

            modelBuilder.Entity("IsbaSatisWeb.Core.Domain.Entities.BankaHareket", b =>
                {
                    b.HasBaseType("IsbaSatisWeb.Core.Domain.Entities.Common.BaseEntity");

                    b.Property<Guid>("BankaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BankaId");

                    b.Property<Guid?>("CariId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CariId");

                    b.Property<string>("FisKodu")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("FisKodu");

                    b.Property<string>("Hareket")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Hareket");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2")
                        .HasColumnName("Tarih");

                    b.Property<decimal?>("Tutar")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("Tutar");

                    b.HasIndex("BankaId");

                    b.HasIndex("CariId");

                    b.ToTable("BankaHareketleri", (string)null);
                });

            modelBuilder.Entity("IsbaSatisWeb.Core.Domain.Entities.Cari", b =>
                {
                    b.HasBaseType("IsbaSatisWeb.Core.Domain.Entities.Common.BaseEntity");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Adres");

                    b.Property<string>("AlisOzelFiyati")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("AlisOzelFiyati");

                    b.Property<string>("CariAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CariAdi");

                    b.Property<string>("CariAltGrubu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("CariAltGrubu");

                    b.Property<string>("CariGrubu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("CariGrubu");

                    b.Property<string>("CariKodu")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("CariKodu");

                    b.Property<string>("CariTuru")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("CariTuru");

                    b.Property<string>("CepTelefonu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CepTelefonu");

                    b.Property<bool>("Durumu")
                        .HasColumnType("bit")
                        .HasColumnName("Durumu");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EMail");

                    b.Property<string>("FaturaUnvani")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FaturaUnvani");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Fax");

                    b.Property<string>("Il")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Il");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Ilce");

                    b.Property<decimal?>("IskontoOrani")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("IskontoOrani");

                    b.Property<string>("OzelKod1")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("OzelKod1");

                    b.Property<string>("OzelKod2")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("OzelKod2");

                    b.Property<string>("OzelKod3")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("OzelKod3");

                    b.Property<string>("OzelKod4")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("OzelKod4");

                    b.Property<decimal?>("RiskLimiti")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("RiskLimiti");

                    b.Property<string>("SatisOzelFiyati")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SatisOzelFiyati");

                    b.Property<string>("Semt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Semt");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Telefon");

                    b.Property<string>("VergiDairesi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("VergiDairesi");

                    b.Property<string>("VergiNo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("VergiNo");

                    b.Property<string>("Web")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("YetkiliKisi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("YetkiliKisi");

                    b.ToTable("Cariler", (string)null);
                });

            modelBuilder.Entity("IsbaSatisWeb.Core.Domain.Entities.Depo", b =>
                {
                    b.HasBaseType("IsbaSatisWeb.Core.Domain.Entities.Common.BaseEntity");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Adres");

                    b.Property<string>("DepoAdi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("DepoAdi");

                    b.Property<string>("DepoKodu")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("DepoKodu");

                    b.Property<string>("Il")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Il");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Ilce");

                    b.Property<string>("Semt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Semt");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Telefon");

                    b.Property<string>("YetkiliAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("YetkiliAdi");

                    b.Property<string>("YetkiliKodu")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("YetkiliKodu");

                    b.ToTable("Depolar", (string)null);
                });

            modelBuilder.Entity("IsbaSatisWeb.Core.Domain.Entities.Fis", b =>
                {
                    b.HasBaseType("IsbaSatisWeb.Core.Domain.Entities.Common.BaseEntity");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Adres");

                    b.Property<decimal?>("Alacak")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("Alacak");

                    b.Property<Guid?>("BankaId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BankaId");

                    b.Property<string>("BelgeNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("BelgeNo");

                    b.Property<decimal?>("Borc")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("Borc");

                    b.Property<Guid?>("CariId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CariId");

                    b.Property<string>("CariTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CepTelefonu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CepTelefonu");

                    b.Property<string>("DepoAdi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("DepoAdi");

                    b.Property<bool>("DepoIrsaliye")
                        .HasColumnType("bit");

                    b.Property<string>("FaturaUnvani")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FaturaUnvani");

                    b.Property<string>("FisBaglantiKodu")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("FisBaglantiKodu");

                    b.Property<string>("FisKodu")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("FisKodu");

                    b.Property<string>("FisTuru")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("FisTuru");

                    b.Property<string>("Il")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Il");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Ilce");

                    b.Property<decimal?>("IskontoOrani")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("IskontoOrani");

                    b.Property<decimal?>("IskontoTutar")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("IskontoTutar");

                    b.Property<Guid?>("PlasiyerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PlasiyerId");

                    b.Property<string>("Semt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Semt");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2")
                        .HasColumnName("Tarih");

                    b.Property<decimal?>("ToplamTutar")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("ToplamTutar");

                    b.Property<string>("VergiDairesi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("VergiDairesi");

                    b.Property<string>("VergiNo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("VergiNo");

                    b.HasIndex("BankaId");

                    b.HasIndex("CariId");

                    b.HasIndex("PlasiyerId");

                    b.ToTable("Fisler", (string)null);
                });

            modelBuilder.Entity("IsbaSatisWeb.Core.Domain.Entities.HizliSatis", b =>
                {
                    b.HasBaseType("IsbaSatisWeb.Core.Domain.Entities.Common.BaseEntity");

                    b.Property<string>("Barkod")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Barkod");

                    b.Property<Guid>("GrupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("UrunAdi");

                    b.ToTable("HizliSatislar", (string)null);
                });

            modelBuilder.Entity("IsbaSatisWeb.Core.Domain.Entities.HizliSatisGrup", b =>
                {
                    b.HasBaseType("IsbaSatisWeb.Core.Domain.Entities.Common.BaseEntity");

                    b.Property<string>("GrupAdi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("GrupAdi");

                    b.ToTable("HizliSatislarGruplari", (string)null);
                });

            modelBuilder.Entity("IsbaSatisWeb.Core.Domain.Entities.Indirim", b =>
                {
                    b.HasBaseType("IsbaSatisWeb.Core.Domain.Entities.Common.BaseEntity");

                    b.Property<string>("Barkod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Barkod");

                    b.Property<DateTime?>("BaslangicTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("BaslangicTarihi");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("BitisTarihi");

                    b.Property<bool>("Durumu")
                        .HasColumnType("bit")
                        .HasColumnName("Durumu");

                    b.Property<decimal>("IndirimOrani")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("IndirimOrani");

                    b.Property<string>("IndirimTuru")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("IndirimTuru");

                    b.Property<string>("StokAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("StokAdi");

                    b.Property<string>("StokKodu")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("StokKodu");

                    b.ToTable("Indirimler", (string)null);
                });

            modelBuilder.Entity("IsbaSatisWeb.Core.Domain.Entities.Kasa", b =>
                {
                    b.HasBaseType("IsbaSatisWeb.Core.Domain.Entities.Common.BaseEntity");

                    b.Property<string>("KasaAdi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("KasaAdi");

                    b.Property<string>("KasaKodu")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("KasaKodu");

                    b.Property<string>("YetkiliAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("YetkiliAdi");

                    b.Property<string>("YetkiliKodu")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("YetkiliKodu");

                    b.ToTable("Kasalar", (string)null);
                });

            modelBuilder.Entity("IsbaSatisWeb.Core.Domain.Entities.KasaHareket", b =>
                {
                    b.HasBaseType("IsbaSatisWeb.Core.Domain.Entities.Common.BaseEntity");

                    b.Property<Guid?>("CariId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CariId");

                    b.Property<string>("FisKodu")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("FisKodu");

                    b.Property<string>("Hareket")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Hareket");

                    b.Property<Guid>("KasaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("KasaId");

                    b.Property<Guid>("OdemeTuruId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OdemeTuruId");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2")
                        .HasColumnName("Tarih");

                    b.Property<decimal?>("Tutar")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("Tutar");

                    b.HasIndex("CariId");

                    b.HasIndex("KasaId");

                    b.HasIndex("OdemeTuruId");

                    b.ToTable("KasaHareketleri", (string)null);
                });

            modelBuilder.Entity("IsbaSatisWeb.Core.Domain.Entities.Kod", b =>
                {
                    b.HasBaseType("IsbaSatisWeb.Core.Domain.Entities.Common.BaseEntity");

                    b.Property<string>("OnEki")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("OnEki");

                    b.Property<int>("SonDeger")
                        .HasColumnType("int")
                        .HasColumnName("SonDeger");

                    b.Property<string>("Tablo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("Tablo");

                    b.ToTable("Kodlar", (string)null);
                });

            modelBuilder.Entity("IsbaSatisWeb.Core.Domain.Entities.OdemeTuru", b =>
                {
                    b.HasBaseType("IsbaSatisWeb.Core.Domain.Entities.Common.BaseEntity");

                    b.Property<string>("OdemeTuruAdi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("OdemeTuruAdi");

                    b.Property<string>("OdemeTuruKodu")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("OdemeTuruKodu");

                    b.ToTable("OdemeTurleri", (string)null);
                });

            modelBuilder.Entity("IsbaSatisWeb.Core.Domain.Entities.Personel", b =>
                {
                    b.HasBaseType("IsbaSatisWeb.Core.Domain.Entities.Common.BaseEntity");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Adres");

                    b.Property<decimal?>("AylikMaasi")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("AylikMaasi");

                    b.Property<bool>("Calisiyor")
                        .HasColumnType("bit")
                        .HasColumnName("Calisiyor");

                    b.Property<string>("CepTelefonu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CepTelefonu");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EMail");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Fax");

                    b.Property<string>("Il")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Il");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Ilce");

                    b.Property<DateTime?>("IseGirisTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("IseGirisTarihi");

                    b.Property<DateTime?>("IstenCikisTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("IstenCikisTarihi");

                    b.Property<string>("PersonelAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PersonelAdi");

                    b.Property<string>("PersonelKodu")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("PersonelKodu");

                    b.Property<decimal?>("PrimOrani")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("PrimOrani");

                    b.Property<string>("Semt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Semt");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("TcKimlikNo");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Telefon");

                    b.Property<string>("Unvani")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("Unvani");

                    b.Property<string>("VergiDairesi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("VergiDairesi");

                    b.Property<string>("VergiNo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("VergiNo");

                    b.Property<string>("Web")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Web");

                    b.ToTable("Personeller", (string)null);
                });

            modelBuilder.Entity("IsbaSatisWeb.Core.Domain.Entities.PersonelHareket", b =>
                {
                    b.HasBaseType("IsbaSatisWeb.Core.Domain.Entities.Common.BaseEntity");

                    b.Property<decimal>("AylikMaasi")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("AylikMaasi");

                    b.Property<DateTime>("Donemi")
                        .HasColumnType("datetime2")
                        .HasColumnName("Donemi");

                    b.Property<string>("FisKodu")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("FisKodu");

                    b.Property<string>("PersonelAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PersonelAdi");

                    b.Property<string>("PersonelKodu")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("PersonelKodu");

                    b.Property<decimal>("PrimOrani")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("PrimOrani");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("TcKimlikNo");

                    b.Property<decimal>("ToplamSatis")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("ToplamSatis");

                    b.Property<string>("Unvani")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("Unvani");

                    b.ToTable("PersonelHareketleri", (string)null);
                });

            modelBuilder.Entity("IsbaSatisWeb.Core.Domain.Entities.SirketBilgi", b =>
                {
                    b.HasBaseType("IsbaSatisWeb.Core.Domain.Entities.Common.BaseEntity");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Adres");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EMail");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Fax");

                    b.Property<string>("Ilcesi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Ilcesi");

                    b.Property<string>("Ili")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Ili");

                    b.Property<string>("Semt")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Semt");

                    b.Property<string>("SirketKisaAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SirketKisaAdi");

                    b.Property<string>("SirketKodu")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("SirketKodu");

                    b.Property<string>("SirketTelNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("SirketTelNo");

                    b.Property<string>("SirketUnvani")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("SirketUnvani");

                    b.Property<string>("Ulkesi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Ulkesi");

                    b.Property<string>("VergiDairesi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("VergiDairesi");

                    b.Property<string>("VergiNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("VergiNo");

                    b.Property<string>("Web")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Web");

                    b.Property<string>("YetkiliKisi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("YetkiliKisi");

                    b.ToTable("SirketBilgileri", (string)null);
                });

            modelBuilder.Entity("IsbaSatisWeb.Core.Domain.Entities.Stok", b =>
                {
                    b.HasBaseType("IsbaSatisWeb.Core.Domain.Entities.Common.BaseEntity");

                    b.Property<decimal?>("AlisFiyati1")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("AlisFiyati1");

                    b.Property<decimal?>("AlisFiyati2")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("AlisFiyati2");

                    b.Property<decimal?>("AlisFiyati3")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("AlisFiyati3");

                    b.Property<int>("AlisKdv")
                        .HasColumnType("int")
                        .HasColumnName("AlisKdv");

                    b.Property<string>("Barkod")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Barkod");

                    b.Property<string>("BarkodTuru")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("BarkodTuru");

                    b.Property<string>("Birimi")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("Birimi");

                    b.Property<bool>("Durumu")
                        .HasColumnType("bit")
                        .HasColumnName("Durumu");

                    b.Property<string>("GarantiSuresi")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("GarantiSüresi");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Marka");

                    b.Property<decimal?>("MaxStokMiktari")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("MaxStokMiktari");

                    b.Property<decimal?>("MinStokMiktari")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("MinStokMiktari");

                    b.Property<string>("Modeli")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Modeli");

                    b.Property<string>("OzelKod1")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("OzelKod1");

                    b.Property<string>("OzelKod2")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("OzelKod2");

                    b.Property<string>("OzelKod3")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("OzelKod3");

                    b.Property<string>("OzelKod4")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("OzelKod4");

                    b.Property<decimal?>("SatisFiyati1")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("SatisFiyati1");

                    b.Property<decimal?>("SatisFiyati2")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("SatisFiyati2");

                    b.Property<decimal?>("SatisFiyati3")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("SatisFiyati3");

                    b.Property<int>("SatisKdv")
                        .HasColumnType("int")
                        .HasColumnName("SatisKdv");

                    b.Property<string>("StokAdi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("StokAdi");

                    b.Property<string>("StokAltGrubu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("StokAltGrubu");

                    b.Property<string>("StokGrubu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("StokGrubu");

                    b.Property<string>("StokKodu")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)")
                        .HasColumnName("StokKodu");

                    b.Property<string>("UreticiKodu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("UreticiKodu");

                    b.ToTable("Stoklar", (string)null);
                });

            modelBuilder.Entity("IsbaSatisWeb.Core.Domain.Entities.StokHareket", b =>
                {
                    b.HasBaseType("IsbaSatisWeb.Core.Domain.Entities.Common.BaseEntity");

                    b.Property<decimal?>("AlisFiyati")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("AlisFiyati");

                    b.Property<decimal?>("AlisFiyati2")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("AlisFiyati2");

                    b.Property<decimal?>("AlisFiyati3")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("AlisFiyati3");

                    b.Property<decimal?>("BirimFiyati")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("BirimFiyati");

                    b.Property<Guid>("DepoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DepoId");

                    b.Property<string>("FisBaglantiKodu")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("FisBaglantiKodu");

                    b.Property<string>("FisKodu")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("FisKodu");

                    b.Property<string>("Hareket")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Hareket");

                    b.Property<decimal?>("IndirimOrani")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("IndirimOrani");

                    b.Property<bool>("Irsaliye")
                        .HasColumnType("bit");

                    b.Property<int>("Kdv")
                        .HasColumnType("int")
                        .HasColumnName("Kdv");

                    b.Property<decimal?>("MevcutStok")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("MevcutStok");

                    b.Property<decimal?>("Miktar")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)");

                    b.Property<decimal?>("SayimMiktari")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("SayimMiktari");

                    b.Property<string>("SeriNo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SeriNo");

                    b.Property<bool>("Siparis")
                        .HasColumnType("bit");

                    b.Property<Guid>("StokId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StokId");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2")
                        .HasColumnName("Tarih");

                    b.Property<bool>("Teklif")
                        .HasColumnType("bit");

                    b.Property<decimal?>("ToplamTutar")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("ToplamTutar");

                    b.HasIndex("DepoId");

                    b.HasIndex("StokId");

                    b.ToTable("StokHareketleri", (string)null);
                });

            modelBuilder.Entity("IsbaSatisWeb.Core.Domain.Entities.Tanim", b =>
                {
                    b.HasBaseType("IsbaSatisWeb.Core.Domain.Entities.Common.BaseEntity");

                    b.Property<string>("Tanimi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Tanimi");

                    b.Property<string>("Turu")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("Turu");

                    b.ToTable("Tanimlar", (string)null);
                });

            modelBuilder.Entity("IsbaSatisWeb.Core.Domain.Entities.BankaHareket", b =>
                {
                    b.HasOne("IsbaSatisWeb.Core.Domain.Entities.Banka", "Banka")
                        .WithMany("BankaHareketler")
                        .HasForeignKey("BankaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IsbaSatisWeb.Core.Domain.Entities.Cari", "Cari")
                        .WithMany("BankaHareketler")
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Banka");

                    b.Navigation("Cari");
                });

            modelBuilder.Entity("IsbaSatisWeb.Core.Domain.Entities.Fis", b =>
                {
                    b.HasOne("IsbaSatisWeb.Core.Domain.Entities.Banka", "banka")
                        .WithMany("Fisler")
                        .HasForeignKey("BankaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IsbaSatisWeb.Core.Domain.Entities.Cari", "Cari")
                        .WithMany("Fisler")
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IsbaSatisWeb.Core.Domain.Entities.Personel", "Personel")
                        .WithMany("Fisler")
                        .HasForeignKey("PlasiyerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cari");

                    b.Navigation("Personel");

                    b.Navigation("banka");
                });

            modelBuilder.Entity("IsbaSatisWeb.Core.Domain.Entities.KasaHareket", b =>
                {
                    b.HasOne("IsbaSatisWeb.Core.Domain.Entities.Cari", "Cari")
                        .WithMany("KasaHareketler")
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IsbaSatisWeb.Core.Domain.Entities.Kasa", "Kasa")
                        .WithMany("KasaHareketler")
                        .HasForeignKey("KasaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IsbaSatisWeb.Core.Domain.Entities.OdemeTuru", "OdemeTuru")
                        .WithMany("KasaHareketler")
                        .HasForeignKey("OdemeTuruId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cari");

                    b.Navigation("Kasa");

                    b.Navigation("OdemeTuru");
                });

            modelBuilder.Entity("IsbaSatisWeb.Core.Domain.Entities.StokHareket", b =>
                {
                    b.HasOne("IsbaSatisWeb.Core.Domain.Entities.Depo", "Depo")
                        .WithMany("StokHareketler")
                        .HasForeignKey("DepoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IsbaSatisWeb.Core.Domain.Entities.Stok", "Stok")
                        .WithMany("StokHareketler")
                        .HasForeignKey("StokId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Depo");

                    b.Navigation("Stok");
                });

            modelBuilder.Entity("IsbaSatisWeb.Core.Domain.Entities.Banka", b =>
                {
                    b.Navigation("BankaHareketler");

                    b.Navigation("Fisler");
                });

            modelBuilder.Entity("IsbaSatisWeb.Core.Domain.Entities.Cari", b =>
                {
                    b.Navigation("BankaHareketler");

                    b.Navigation("Fisler");

                    b.Navigation("KasaHareketler");
                });

            modelBuilder.Entity("IsbaSatisWeb.Core.Domain.Entities.Depo", b =>
                {
                    b.Navigation("StokHareketler");
                });

            modelBuilder.Entity("IsbaSatisWeb.Core.Domain.Entities.Kasa", b =>
                {
                    b.Navigation("KasaHareketler");
                });

            modelBuilder.Entity("IsbaSatisWeb.Core.Domain.Entities.OdemeTuru", b =>
                {
                    b.Navigation("KasaHareketler");
                });

            modelBuilder.Entity("IsbaSatisWeb.Core.Domain.Entities.Personel", b =>
                {
                    b.Navigation("Fisler");
                });

            modelBuilder.Entity("IsbaSatisWeb.Core.Domain.Entities.Stok", b =>
                {
                    b.Navigation("StokHareketler");
                });
#pragma warning restore 612, 618
        }
    }
}
